
// (( IN 'C'  WE CAN NOT PUT FUNCTIONS IN THE STRUCTERS BUT WE CAN ))
//(( DO IN 'C++' WE CAN PUT FINCTION))
//(( IN CLASS ALL MEMBERS ARE BY DEALUT PRIVATE ))
// (( IN STRUCT ALL MEMBERS ARE ARE NOT BY DEALUT PUBLIC))